version: '3.8'

services:
  # SweynTooth 서비스 정의 (Python 2.7 기반)
  sweyntooth:
    build:
      context: ./sweyntooth
    container_name: sweyntooth
    privileged: true # nRF52 동글 등 하드웨어 직접 접근 권한
    tty: true        # 터미널 유지
    stdin_open: true # 표준 입력 활성화
    volumes:
      - ./sweyntooth/logs:/logs # 로그 폴더를 호스트와 공유

  # BLE GATT Fuzzing 서비스 정의 (Python 3.10 기반)
  fuzzer:
    build:
      context: ./ble-gatt-fuzzing
    container_name: fuzzer
    network_mode: "host" # 호스트의 네트워크(블루투스 포함)를 그대로 사용
    privileged: true     # 호스트 장치 접근 권한
    tty: true
    stdin_open: true
